version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.26
    working_directory: /go/src/github.com/tellytv/go.xtream-codes
    steps:
      - checkout
      - run: go build ./...
      - run: go vet ./...
      - run: go test -v ./...
